Draft: Prettier hook
avlos/dotfiles pull request #7
Opened 2021-11-15 15:53 UTC by vchaldeakis

2021-11-15 19:36 UTC, chemeng commented on .pre-commit-config.yaml
> +    - id: prettier
don't wee need a configuration for prettier? also shouldn't we add eslint as well in addition to formatting?

2021-11-16 08:43 UTC, vchaldeakis commented on .pre-commit-config.yaml
> +    - id: prettier
i added eslint [today](https://github.com/avlos/dotfiles/pull/7/commits/b8c28f91cb40b71feaf685a45f174b5708895ad3). about prettier, reading the [docs](https://prettier.io/docs/en/configuration.html), everything we want is included (my opinion)

2021-11-16 11:12 UTC, chemeng reviewed
looks good to me (assuming the default prettierc config is ok for us). @estebanz01 / @shamangeorge anything else we'd like for vuejs/javascript/html linting/formatting?

2021-11-17 15:27 UTC, estebanz01 commented on .pre-commit-config.yaml
> +    - id: prettier
is prettier like black? Where can I see their opinions? does it enforce the [airbnb style we have defined](https://operations.avlos.tech/engineering-handbook/code_quality/code_styling/) ?

2021-11-17 15:27 UTC, estebanz01 commented on .pre-commit-config.yaml
> +    - id: prettier
also, following the question by tim: Don't we need a default configuration file for this?

2021-11-18 06:37 UTC, vchaldeakis commented on .pre-commit-config.yaml
> +    - id: prettier
good morning Este!  
correct! as far as i understand by reading it, prettier is like black. i used it before eslint so that it formats the code but there is no error checking from it. it's options you can see [here](https://prettier.io/docs/en/options.html).  
about the airbnb, i added airbnb in linter

2021-11-18 15:17 UTC, estebanz01 commented on .pre-commit-config.yaml
> +    - id: prettier
ok, I think we might going to have some conflicts between linters and prettier. We need a default configuration that overrides:

* Line width to 100.
* Force single quotes.
* No trailing commas.
* Closing bracket on the same line.
* Indent vue script and style tags.

2021-11-24 13:23 UTC, vchaldeakis commented
@chemeng @estebanz01 @shamangeorge   
with the last commit i tried to understand better the pre-commit solution and created a separate file `eslintrc.js` to contain the information

2021-11-26 15:31 UTC, estebanz01 commented
Let's fix the codacy issues this PR has before doing a deep review again @vchaldeakis

2021-12-07 10:00 UTC, vchaldeakis commented
@chemeng @estebanz01 @shamangeorge could you please review this once more?

2021-12-07 16:00 UTC, estebanz01 requested changes
Let's also update all your commits to conform with the avlos commit message styleguide.

2021-12-08 12:49 UTC, vchaldeakis commented on .eslintrc.js
> +      files: ['**/__tests__/*.{j,t}s?(x)', '**/tests/unit/**/*.spec.{j,t}s?(x)'],
as far as i know, in frontend frameworks (especially vuejs) tests are in a directory called `tests`

2021-12-09 19:33 UTC, estebanz01 commented on .eslintrc.js
> +      files: ['**/__tests__/*.{j,t}s?(x)', '**/tests/unit/**/*.spec.{j,t}s?(x)'],
can you add `**/specs/**/*_spec.{j,t}s?` then ?

2021-12-15 14:46 UTC, vchaldeakis commented on .eslintrc.js
> +      files: ['**/__tests__/*.{j,t}s?(x)', '**/tests/unit/**/*.spec.{j,t}s?(x)'],
fixed and squashed commits

2021-12-15 15:43 UTC, estebanz01 approved these changes

2021-12-15 15:56 UTC, chemeng commented
@vchaldeakis is this still draft? if yes what's pending?

2021-12-15 16:21 UTC, vchaldeakis commented
> @vchaldeakis is this still draft? if yes what's pending?

Added what Esteban suggested and from my part, I think it is ready.

2021-12-15 16:38 UTC, merged